-- À exécuter une fois dans l'éditeur SQL de Supabase.
create table if not exists public.workshops (
  id text primary key,
  state jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  updated_by_email text
);

create table if not exists public.workshop_members (
  workshop_id text not null,
  email text not null,
  role text not null default 'organizer',
  created_at timestamptz not null default now(),
  primary key (workshop_id, email)
);

create table if not exists public.workshop_audit_logs (
  id bigint generated by default as identity primary key,
  workshop_id text not null,
  actor_id uuid references auth.users(id),
  actor_email text,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.workshops enable row level security;
alter table public.workshops replica identity full;
alter table public.workshop_members enable row level security;
alter table public.workshop_audit_logs enable row level security;

drop function if exists public.is_workshop_member(text);
create function public.is_workshop_member(target_workshop_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.workshop_members member
    where member.workshop_id = target_workshop_id
      and lower(member.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

drop policy if exists "authenticated users can read workshops" on public.workshops;
drop policy if exists "workshop members can read workshops" on public.workshops;
create policy "workshop members can read workshops"
on public.workshops for select
to authenticated
using (public.is_workshop_member(id));

drop policy if exists "authenticated users can create workshops" on public.workshops;
drop policy if exists "workshop members can create workshops" on public.workshops;
create policy "workshop members can create workshops"
on public.workshops for insert
to authenticated
with check (public.is_workshop_member(id));

drop policy if exists "authenticated users can update workshops" on public.workshops;
drop policy if exists "workshop members can update workshops" on public.workshops;
create policy "workshop members can update workshops"
on public.workshops for update
to authenticated
using (public.is_workshop_member(id))
with check (public.is_workshop_member(id));

drop policy if exists "members can read their own membership" on public.workshop_members;
create policy "members can read their own membership"
on public.workshop_members for select
to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists "workshop members can read audit logs" on public.workshop_audit_logs;
create policy "workshop members can read audit logs"
on public.workshop_audit_logs for select
to authenticated
using (public.is_workshop_member(workshop_id));

drop policy if exists "workshop members can create audit logs" on public.workshop_audit_logs;
create policy "workshop members can create audit logs"
on public.workshop_audit_logs for insert
to authenticated
with check (
  public.is_workshop_member(workshop_id)
  and actor_id = auth.uid()
  and lower(actor_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'workshops'
  ) then
    alter publication supabase_realtime add table public.workshops;
  end if;
end $$;

-- Mutations atomiques pour la boutique. L'application cliente peut les appeler
-- via supabase.rpc afin que deux organisateurs ne dépensent jamais le même solde.
create or replace function public.record_shop_purchase(target_workshop_id text, target_team_id text, purchase jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare current_state jsonb; total numeric; team_budget numeric; spent numeric;
begin
  if not public.is_workshop_member(target_workshop_id) then raise exception 'organisateur non autorisé'; end if;
  select state into current_state from public.workshops where id = target_workshop_id for update;
  total := (purchase->>'amount')::numeric;
  team_budget := coalesce((select (p->>'budget')::numeric from jsonb_array_elements(current_state->'problems') p where (p->>'id')::int = (select (t->>'problemId')::int from jsonb_array_elements(current_state->'teams') t where t->>'id'=target_team_id)), 0);
  spent := coalesce((select sum((p->>'amount')::numeric) from jsonb_array_elements(current_state->'purchases') p where p->>'teamId'=target_team_id and not (p ? 'cancelledAt')), 0);
  if total < 0 or spent + total > team_budget then raise exception 'budget insuffisant'; end if;
  update public.workshops set state = jsonb_set(current_state, '{purchases}', (current_state->'purchases') || jsonb_build_array(purchase), true), updated_at=now() where id=target_workshop_id;
  return purchase;
end; $$;

-- Optionnel : les organisateurs peuvent créer plusieurs ateliers en changeant
-- NEXT_PUBLIC_WORKSHOP_ID dans les variables d'environnement Vercel.

-- Important : ajoutez au moins un organisateur avant la première connexion.
-- Remplacez l'e-mail par celui qui recevra le lien magique.
--
-- insert into public.workshop_members (workshop_id, email, role)
-- values ('atelier-principal', 'organisateur@example.com', 'owner')
-- on conflict (workshop_id, email) do update set role = excluded.role;
